name: Deploy to S3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIA3M7AC77V7R3IJSXN }}
          aws-secret-access-key: ${{ secrets.YMOGUczPH77NCrxWbh7q8ZFuzgycF6+NDJf3fucc }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: aws s3 sync . s3://cmtr-aiur8t3l-bucket-1755350999 --delete
